# ---------------------------------------------------------
# KITTY CONFIGURATION
# ---------------------------------------------------------
# -- Colors -- #
include colors/colors.conf

# -- Fonts -- #
font_family                     JetBrainsMono Nerd Font
bold_font                       auto
italic_font                     auto
bold_italic_font                auto
font_size                       9
disable_ligatures               never
force_ltr                       no

# -- Background -- #
background_opacity              0.9
dynamic_background_opacity      yes


# -- URLs -- #
url_style                       curly
url_prefixes                    http https file ftp
detect_urls                     yes
open_url_with                   default
underline_hyperlinks            always

# -- Performance -- #
sync_to_monitor                 yes
repaint_delay                   10
input_delay                     3

# -- Cursor -- #
cursor_shape                    underline 
cursor_underline_thickness      1
cursor_trail                    1
cursor_trail_start_threshold    0
cursor_trail_decay              0.1 0.8
cursor_blink_interval           0.5 ease-in
cursor_stop_blinking_after      8
cursor_shape_unfocused          underline

# -- Terminal bell -- #
enable_audio_bell               no
window_alert_on_bell            yes
visual_bell_duration            0.15
visual_bell_color               #1a1a2e

# -- Shell & Integration -- #
shell                           fish
shell_integration               no-cursor
confirm_os_window_close         0

# -- Window Layout -- #
remember_window_size            no
initial_window_width            259c
initial_window_height           58c
window_padding_width            15           
hide_window_decorations         yes
placement_strategy              center
inactive_text_alpha             0.8

# -- Scrollback -- #
scrollback_lines                10000
scrollbar never

# -- Scrolling -- #
wheel_scroll_multiplier         3.0
touch_scroll_multiplier         3.0
pixel_scroll                    yes
momentum_scroll                 0.96

# -- Clipboard -- #
clipboard_control               write-clipboard read-clipboard
copy_on_select                  yes

# -- Safety / Paste -- #
paste_actions                   quote-urls-at-prompt,confirm,confirm-if-large
strip_trailing_spaces           smart

# -- Mouse behavior -- #
mouse_hide_wait                 -1.0
focus_follows_mouse             no
default_pointer_shape           beam
pointer_shape_when_grabbed      arrow
pointer_shape_when_dragging     beam crosshair

# -- Scrollback / Pager -- #
scrollback_pager                less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size   20
scrollback_fill_enlarged_window yes