#!/usr/bin/env bash
# ============================================================================
#  apply-static-colors.sh — applies the static "Kitasan Glass" palette
# ----------------------------------------------------------------------------
#  Two uses:
#   1) Bootstrap on a fresh clone: the per-app color files are generated by
#      matugen and do NOT live in the repo — only their *.static.*
#      counterparts do. Running this once after cloning leaves the system
#      with the static identity, identical to how it looks with dynamic
#      theming turned off (the default state).
#   2) Restoration when turning matugen off: rofi/scripts/matugen_toggle.sh
#      calls this same script instead of duplicating the copy list.
#
#  The daemon reloads (waybar/kitty/swaync) are guarded with "|| true" on
#  purpose: on a freshly installed clone those processes aren't running
#  yet, and that shouldn't fail the bootstrap.
# ============================================================================

set -u

cp "$HOME/.config/rofi/colors.static.rasi"         "$HOME/.config/rofi/colors.rasi"          2>/dev/null || true
cp "$HOME/.config/waybar/colors.static.css"        "$HOME/.config/waybar/colors.css"         2>/dev/null || true
cp "$HOME/.config/wlogout/colors.static.css"       "$HOME/.config/wlogout/colors.css"        2>/dev/null || true
cp "$HOME/.config/hyprlock/colors.static.conf"     "$HOME/.config/hyprlock/colors.conf"      2>/dev/null || true
cp "$HOME/.config/kitty/colors/colors.static.conf" "$HOME/.config/kitty/colors/colors.conf"  2>/dev/null || true
cp "$HOME/.config/swaync/colors.static.css"        "$HOME/.config/swaync/colors.css"         2>/dev/null || true
cp "$HOME/.config/starship.static.toml"            "$HOME/.config/starship.toml"             2>/dev/null || true
cp "$HOME/.config/fish/theme-goldship.static.fish" "$HOME/.config/fish/conf.d/theme-goldship.fish" 2>/dev/null || true
cp "$HOME/.config/hyprlock/scripts/music-colors.static.sh" "$HOME/.config/hyprlock/scripts/music-colors.sh" 2>/dev/null || true
cp "$HOME/.config/gtk-3.0/gtk-colors.static.css"    "$HOME/.config/gtk-3.0/gtk-colors.css"    2>/dev/null || true
cp "$HOME/.config/gtk-4.0/gtk-colors.static.css"    "$HOME/.config/gtk-4.0/gtk-colors.css"    2>/dev/null || true
cp "$HOME/.config/qt5ct/colors/kitasan-glass.static.conf" "$HOME/.config/qt5ct/colors/kitasan-glass.conf" 2>/dev/null || true
cp "$HOME/.config/qt6ct/colors/kitasan-glass.static.conf" "$HOME/.config/qt6ct/colors/kitasan-glass.conf" 2>/dev/null || true

STATIC_HYPR="$HOME/.config/hypr/scripts/dynamic-colors.static.sh"
[ -x "$STATIC_HYPR" ] && bash "$STATIC_HYPR"

# Acá vivía la recreación del symlink gtk-4.0/theme-base.css, que apuntaba al
# gtk.css del tema GTK de terceros que estuviera activo. Ya no hace falta y se
# quitó: GTKTheme es Adwaita-dark (stock), así que no hay tema externo que
# encadenar — GTK3 lo carga por la env var GTK_THEME y GTK4 lo trae libadwaita
# incorporado. gtk-3.0/gtk.css y gtk-4.0/gtk.css son hoy un único
# @import 'gtk-colors.css', y ese archivo lo escribe el bloque de copias de
# arriba (o matugen, si el dinámico está encendido). Ver
# docs/THEMING.md § GTK theming.

# Hyprlock background: bootstrap from the static 2.png only if there's no
# current.png yet — doesn't override the user's actual choice if it already
# exists (picking a wallpaper updates current.png independently of the
# matugen toggle, so turning the toggle off should never revert it).
[ -f "$HOME/.config/hyprlock/wallpapers/current.png" ] || \
    cp "$HOME/.config/hyprlock/wallpapers/2.png" "$HOME/.config/hyprlock/wallpapers/current.png" 2>/dev/null || true

pkill -SIGUSR2 waybar 2>/dev/null || true
killall -SIGUSR1 kitty 2>/dev/null || true
command -v swaync-client >/dev/null 2>&1 && swaync-client -rs >/dev/null 2>&1 || true
