#!/usr/bin/env bash
# ============================================================================
#  apply-static-colors.sh — applies the static "Kitasan Glass" palette
# ----------------------------------------------------------------------------
#  Two uses:
#   1) Bootstrap on a fresh clone: the per-app color files are generated by
#      matugen and do NOT live in the repo — only their *.static.*
#      counterparts do. Running this once after cloning leaves the system
#      with the static identity, identical to how it looks with dynamic
#      theming turned off (the default state).
#   2) Restoration when turning matugen off: rofi/scripts/matugen_toggle.sh
#      calls this same script instead of duplicating the copy list.
#
#  The daemon reloads (waybar/kitty/swaync) are guarded with "|| true" on
#  purpose: on a freshly installed clone those processes aren't running
#  yet, and that shouldn't fail the bootstrap.
# ============================================================================

set -u

cp "$HOME/.config/rofi/colors.static.rasi"         "$HOME/.config/rofi/colors.rasi"          2>/dev/null || true
cp "$HOME/.config/waybar/colors.static.css"        "$HOME/.config/waybar/colors.css"         2>/dev/null || true
cp "$HOME/.config/wlogout/colors.static.css"       "$HOME/.config/wlogout/colors.css"        2>/dev/null || true
cp "$HOME/.config/hyprlock/colors.static.conf"     "$HOME/.config/hyprlock/colors.conf"      2>/dev/null || true
cp "$HOME/.config/kitty/colors/colors.static.conf" "$HOME/.config/kitty/colors/colors.conf"  2>/dev/null || true
cp "$HOME/.config/swaync/colors.static.css"        "$HOME/.config/swaync/colors.css"         2>/dev/null || true
cp "$HOME/.config/starship.static.toml"            "$HOME/.config/starship.toml"             2>/dev/null || true
cp "$HOME/.config/fish/theme-goldship.static.fish" "$HOME/.config/fish/conf.d/theme-goldship.fish" 2>/dev/null || true
cp "$HOME/.config/hyprlock/scripts/music-colors.static.sh" "$HOME/.config/hyprlock/scripts/music-colors.sh" 2>/dev/null || true
cp "$HOME/.config/gtk-3.0/gtk-colors.static.css"    "$HOME/.config/gtk-3.0/gtk-colors.css"    2>/dev/null || true
cp "$HOME/.config/gtk-4.0/gtk-colors.static.css"    "$HOME/.config/gtk-4.0/gtk-colors.css"    2>/dev/null || true
cp "$HOME/.config/qt5ct/colors/kitasan-glass.static.conf" "$HOME/.config/qt5ct/colors/kitasan-glass.conf" 2>/dev/null || true
cp "$HOME/.config/qt6ct/colors/kitasan-glass.static.conf" "$HOME/.config/qt6ct/colors/kitasan-glass.conf" 2>/dev/null || true

STATIC_HYPR="$HOME/.config/hypr/scripts/dynamic-colors.static.sh"
[ -x "$STATIC_HYPR" ] && bash "$STATIC_HYPR"

# gtk-4.0/theme-base.css: symlink to the real theme (whatever GTKTheme
# declares in hypr/modules/environment.lua — currently Win11-Fantasy-Dark),
# deliberately NOT versioned — it's a third-party file installed in
# ~/.themes/ or ~/.local/share/themes/, not something this repo should
# publish, and an absolute symlink with the username hardcoded wouldn't
# survive a clone on another machine either. Recreated here (idempotent)
# so a fresh clone's bootstrap leaves gtk-4.0/gtk.css working without
# depending on theme-base.css having survived the clone.
#
# The theme name is read from environment.lua instead of being hardcoded
# here too — GTKTheme changed from Colorful-Dark-GTK to Win11-Fantasy-Dark
# once and this script was left pointing at the old theme (broken
# symlinks) until someone noticed by hand. With this, changing the theme
# in one place is enough. Both standard locations are searched because
# nwg-look installs in ~/.themes/ but other installers use
# ~/.local/share/themes/.
ENV_LUA="$HOME/.config/hypr/modules/environment.lua"
GTK_THEME_NAME=$(grep -oP '(?<=^GTKTheme = ")[^"]+' "$ENV_LUA" 2>/dev/null)
if [ -n "$GTK_THEME_NAME" ]; then
    for base in "$HOME/.themes" "$HOME/.local/share/themes"; do
        THEME_GTK4="$base/$GTK_THEME_NAME/gtk-4.0/gtk.css"
        if [ -f "$THEME_GTK4" ]; then
            ln -sf "$THEME_GTK4" "$HOME/.config/gtk-4.0/theme-base.css" 2>/dev/null || true
            break
        fi
    done
fi

# Hyprlock background: bootstrap from the static 2.png only if there's no
# current.png yet — doesn't override the user's actual choice if it already
# exists (picking a wallpaper updates current.png independently of the
# matugen toggle, so turning the toggle off should never revert it).
[ -f "$HOME/.config/hyprlock/wallpapers/current.png" ] || \
    cp "$HOME/.config/hyprlock/wallpapers/2.png" "$HOME/.config/hyprlock/wallpapers/current.png" 2>/dev/null || true

pkill -SIGUSR2 waybar 2>/dev/null || true
killall -SIGUSR1 kitty 2>/dev/null || true
command -v swaync-client >/dev/null 2>&1 && swaync-client -rs >/dev/null 2>&1 || true
