function quickcache --description "Quick safe cache cleanup with animated confirmation"
    clear

    function __quickcache_type
        set -l text "$argv[1]"
        set -l delay 0.012

        if test (count $argv) -ge 2
            set delay "$argv[2]"
        end

        for char in (string split '' -- "$text")
            printf "%s" "$char"
            sleep "$delay"
        end

        echo ""
    end

    function __quickcache_header
        set_color cyan
        __quickcache_type "󰪺 Quick Cache Cleanup" 0.015
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        set_color normal
    end

    function __quickcache_section
        echo ""
        set_color yellow
        __quickcache_type "$argv[1]" 0.01
        set_color normal
    end

    __quickcache_header

    set -l targets \
        "$HOME/.cache/BraveSoftware" \
        "$HOME/.cache/spotify" \
        "$HOME/.cache/thumbnails" \
        "$HOME/.cache/mesa_shader_cache" \
        "$HOME/.cache/yay" \
        "$HOME/.cache/pip" \
        "$HOME/.cache/electron" \
        "$HOME/.cache/go-build" \
        "$HOME/.cache/cliphist" \
        "$HOME/.codex/.tmp"

    echo ""
    set_color brblack
    __quickcache_type "Scanning known regenerable cache folders..." 0.01
    set_color normal

    echo ""

    set -l found 0

    for target in $targets
        if test -e "$target"
            set found 1
            du -sh "$target" 2>/dev/null
        end
    end

    if test "$found" = 0
        echo ""
        set_color green
        __quickcache_type "✅ No known cache folders found." 0.015
        set_color normal
        echo ""
        read -P "Press Enter to exit..."
        return 0
    end

    echo ""
    set_color red
    __quickcache_type "This will delete the cache folders listed above." 0.018
    set_color normal

    set_color brblack
    __quickcache_type "These are expected to be regenerated by their apps." 0.012
    set_color normal

    echo ""
    read -P "Delete listed cache folders? [y/N] > " confirm

    if not test "$confirm" = "y" -o "$confirm" = "Y"
        echo ""
        set_color brblack
        __quickcache_type "Cancelled." 0.015
        set_color normal
        echo ""
        read -P "Press Enter to exit..."
        return 0
    end

    __quickcache_section "󰆴 Removing cache folders"

    for target in $targets
        if test -e "$target"
            set -l target_real (realpath "$target" 2>/dev/null)

            if test -z "$target_real"
                set_color red
                echo "Skipping unsafe path: $target"
                set_color normal
                continue
            end

            switch "$target_real"
                case "$HOME/.cache/"\* "$HOME/.codex/.tmp"
                    set_color yellow
                    echo "Removing: $target_real"
                    set_color normal
                    rm -rf -- "$target_real"

                    set_color green
                    echo "Removed."
                    set_color normal

                case '*'
                    set_color red
                    echo "Refusing unsafe path: $target_real"
                    set_color normal
            end
        end
    end

    if type -q cliphist
        echo ""
        set_color magenta
        __quickcache_type "󰅇 Cliphist detected." 0.012
        set_color normal

        set_color brblack
        __quickcache_type "This clears clipboard history stored by cliphist." 0.012
        set_color normal

        read -P "Run 'cliphist wipe'? [y/N] > " clean_cliphist

        if test "$clean_cliphist" = "y" -o "$clean_cliphist" = "Y"
            cliphist wipe
            set_color green
            __quickcache_type "cliphist wiped." 0.015
            set_color normal
        else
            set_color brblack
            echo "Skipped cliphist wipe."
            set_color normal
        end
    end

    if type -q npm
        echo ""
        set_color magenta
        __quickcache_type " npm detected." 0.012
        set_color normal

        set_color brblack
        __quickcache_type "This clears npm download cache." 0.012
        set_color normal

        read -P "Clean npm cache? [y/N] > " clean_npm

        if test "$clean_npm" = "y" -o "$clean_npm" = "Y"
            npm cache clean --force
            set_color green
            __quickcache_type "npm cache cleaned." 0.015
            set_color normal
        else
            set_color brblack
            echo "Skipped npm cache."
            set_color normal
        end
    end

    echo ""
    set_color green
    __quickcache_type "✅ Quick cache cleanup complete." 0.018
    set_color normal

    echo ""
    read -P "Press Enter to exit..."
end