#!/usr/bin/env bash
# Generated by matugen — do not edit by hand.
# Applies the Hyprland border on the fly via `hyprctl eval` + hl.config()
# (confirmed live: `hyprctl keyword` is rejected by the Lua parser;
# neither `hyprctl reload` nor `reload full-reset` re-run `require`d
# modules, so this is the only mechanism that actually applies the change
# immediately).
#
# "Fully dynamic": the active border is a gradient between the wallpaper's
# accent and secondary colors (no longer white). The inactive one is the
# accent at low alpha — still subtle, but no longer a fixed white.
# Static reference: ~/.config/hypr/scripts/dynamic-colors.static.sh

hyprctl eval 'hl.config({
  general = {
    col = {
      active_border   = { colors = {"rgba({{colors.primary.default.hex_stripped}}cc)", "rgba({{colors.secondary.default.hex_stripped}}99)"}, angle = 45 },
      inactive_border = "rgba({{colors.primary.default.hex_stripped}}0f)",
    },
  },
})' >/dev/null 2>&1 || true
