# Kitasan Glass — dynamic colors for the Hyprlock music bar.
# Generated by matugen. Static reference:
# ~/.config/hyprlock/scripts/music-colors.static.sh
COLOR_PLAYED="{{colors.primary.default.hex}}"
COLOR_REMAINING="{{colors.on_surface.default.hex_alpha | set_alpha: 0.25}}"
COLOR_HANDLE="{{colors.on_surface.default.hex}}"
