# ~/.config/fish/conf.d/theme-goldship.fish
# Kitasan · Glass Universal · Fish shell theme (dynamic)
# Generated by matugen — do not edit by hand.
# Static reference: ~/.config/fish/theme-goldship.static.fish
#
# Real limitation: fish only reads conf.d/ when a shell STARTS — there's no
# hot-reload signal like in kitty/waybar. Already-open terminals keep the
# old colors until you open a new one.

# ── Syntax: core ──────────────────────────────────────────────
set -g fish_color_normal          {{colors.on_surface.default.hex_stripped}}
set -g fish_color_command         {{colors.primary.default.hex_stripped}}
set -g fish_color_builtin         {{colors.tertiary.default.hex_stripped}}
set -g fish_color_keyword         {{colors.secondary.default.hex_stripped}}
set -g fish_color_end             {{colors.outline.default.hex_stripped}}
set -g fish_color_error           {{colors.error.default.hex_stripped}}

# ── Syntax: arguments & operators ───────────────────────────
set -g fish_color_param           {{colors.on_surface_variant.default.hex_stripped}}
set -g fish_color_option          {{colors.outline.default.hex_stripped}}
set -g fish_color_operator        {{colors.on_secondary_container.default.hex_stripped}}
set -g fish_color_redirection     {{colors.outline_variant.default.hex_stripped}}
set -g fish_color_escape          {{colors.on_surface.default.hex_stripped}}
set -g fish_color_quote           {{colors.on_tertiary_container.default.hex_stripped}}

# ── Syntax: structure ────────────────────────────────────────
set -g fish_color_comment         {{colors.outline.default.hex_stripped}}
set -g fish_color_bracket         {{colors.on_secondary_container.default.hex_stripped}}

# ── Paths ─────────────────────────────────────────────────────
set -g fish_color_valid_path      {{colors.on_surface.default.hex_stripped}} --underline
set -g fish_color_cwd             {{colors.on_surface_variant.default.hex_stripped}}
set -g fish_color_cwd_root        {{colors.secondary.default.hex_stripped}}

# ── Autosuggestions & history ───────────────────────────────
set -g fish_color_autosuggestion  {{colors.outline_variant.default.hex_stripped}}
set -g fish_color_history_current {{colors.on_surface.default.hex_stripped}} --bold
set -g fish_color_cancel          {{colors.error.default.hex_stripped}}

# ── Search & selection ────────────────────────────────────────
set -g fish_color_search_match    {{colors.on_surface.default.hex_stripped}} --background={{colors.surface_container_high.default.hex_stripped}}
set -g fish_color_selection       {{colors.on_surface.default.hex_stripped}} --background={{colors.surface_container.default.hex_stripped}}
set -g fish_color_match           {{colors.tertiary.default.hex_stripped}}

# ── Prompt: user & host ───────────────────────────────────────
set -g fish_color_user            {{colors.on_surface.default.hex_stripped}}
set -g fish_color_host            {{colors.outline.default.hex_stripped}}
set -g fish_color_host_remote     {{colors.on_tertiary_container.default.hex_stripped}}

# ── Prompt: status ────────────────────────────────────────────
set -g fish_color_status          {{colors.error.default.hex_stripped}}

# ── Completions pager ─────────────────────────────────────────
set -g fish_pager_color_progress              {{colors.outline_variant.default.hex_stripped}}
set -g fish_pager_color_prefix                {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_completion            {{colors.on_surface_variant.default.hex_stripped}}
set -g fish_pager_color_description           {{colors.outline.default.hex_stripped}}
set -g fish_pager_color_secondary             {{colors.outline_variant.default.hex_stripped}}

set -g fish_pager_color_selected_background   --background={{colors.surface_container.default.hex_stripped}}
set -g fish_pager_color_selected_prefix       {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_selected_completion   {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_selected_description  {{colors.tertiary.default.hex_stripped}}
